### ISSUE TITLE
Shading of dual axis trackers

### ISSUE THREAD

**Issue by AdamRJensen** [isi-ies-group/cpvlib#11]
I just wanted to inform you that the pvlib organization has a new package called [twoaxistracking](https://twoaxistracking.readthedocs.io/).

The package provides a set of tools for determining field layouts of two-axis trackers and calculating the shaded fraction for any given sun position.

From what I can tell this package does not account for shading, and maybe shouldn't, but at least it's something to consider.

**Comment by rubennj** [comment]
Hi Adam! It's good to know that there are more packages in the pvlib environment. I'm sure it can be useful at any time.
Thanks.
