### ISSUE TITLE
function pvlib.pvsystem.pvsyst_celltemp() is deprecated

### ISSUE THREAD

**Issue by Piranias** [isi-ies-group/cpvlib#5]
The function was moved into pvlib.temperature.pvsyst_cell()

This needs to be updated in [cpvlib.py](https://github.com/isi-ies-group/cpvlib/blob/master/cpvlib/cpvlib.py#L187)

**Comment by rubennj** [comment]
fixed replacing the call with the new location

**Comment by rubennj** [comment]
Fixed and now passing tests
